export const ADD_NEW_USER = "ADD_NEW_USER";
export const SEND_VALIDATED_USER = "SEND_VALIDATED_USER";
export const DISCONNECTED_USER = "DISCONNECTED_USER";
export const RECEIVE_NEW_MESSAGE = "RECEIVE_NEW_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const ADD_CONNECTED_USERS = "ADD_CONNECTED_USERS";




